### ISSUE TITLE
The secret is saved in json file?!

### ISSUE THREAD

**Issue by Hary309** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#1]
Hi, I liked the idea behind this plugin but I decided to check how it works before exposing myself to potential treat. 
While looking at this code I noticed that you are saving the user's secret to json file, I am not really into C# but this looks very bad.

https://github.com/RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch/blob/8b0db28d6436d03487913e34907a0d9020e1d053/BitwardenFlowSettings.cs#L17C2-L29

The standard bitwarden application requires from user to login every time the application restarts, it would be nice to have something like this in this plugin.

Anyway, thanks for the work!

**Comment by RedMageKnight** [comment]
Hi @Hary309,

Thank you for brining it to my attention, I'm glad you took a look at it and could confirm that this is probably not the best way to handle it even when using a SecureString due to its serialization when converted to the JSON property.

I'm going to make some adjustments to it - make it so that it uses Windows Credentials Manager to store the secret instead of serializing it to disk - I'll update it soon.

**Comment by RedMageKnight** [comment]
Hi @Hary309,

My changes are now complete - go ahead and review it again if you'd like, but I'm using Windows Credential Manager now to handle the secret and also made a few other fixes in 1.1.0 which should show up in the plugin store in a little while I imagine. Lock timeouts and initial logins will always require the master password, so it should never remain unlocked unless you decide to keep the session saved permanently (which is an option, but not the default - default is to retain the session for 5 minutes before clearing it). 

Even in this scenario - only the session key is stored, which is documented practice per Bitwarden's CLI documentation and can be easily cleared at any time by manually locking the vault from the plugin or setting a timeout or restarting Flow Launcher itself.

I hope this looks better to you and should you decide to eventually use the plugin, I hope it's useful to you and always appreciate any feedback on improvements or features :)

**Comment by Hary309** [comment]
Thanks for the changes! It looks better but I still think that keeping the master password somewhere on the computer is a bad idea. From what I have read, the Windows Credential Manager is only encrypted if the user is not logged in, so it may be a vector of attack.

I know entering the password every a while to unlock the vault is not the most convenient way of using the app but this is the cost of good security.

Thanks for your contribution to the Flow Launcher ecosystem!

PS:
I noticed that you have implemented your Logger but while reading the documentation of the Flow Launcher plugin API I noticed that it has an API to log some messages (LogDebug, LogException, LogInfo, LogWarn).
https://www.flowlauncher.com/docs/#/API-Reference/Flow.Launcher.Plugin/IPublicAPI

**Comment by RedMageKnight** [comment]
Hi @Hary309!

Thank you for your input and suggestions! This has been a fun project for me, it's the first time I'm putting one of my personal projects out in the wild, so it's been a great learning opportunity for me to adjust my code in a way that is more conscientious to public needs and concerns!

To address you concerns about the master password - I'm not actually storing the master password anywhere - it's being provided via the plugin <code>/unlock</code> to solely be passed to the Bitwarden CLI as the unlock mechanism and is then being discarded. Similar to how you would enter your master password when authenticating directly into the CLI from command-line. 

What is being stored is the client_secret value from the API which is being stored in Windows Credentials Manager. You're absolutely right regarding the encryption of WCM, but to alleviate some concern, this can only be accessed only when you have administrative rights to the machine or in knowing the user's device username and password. If this is compromised, likely the rest of your computer is already compromised, but I understand the want to reduce attack vectors as much as possible while still maintaining convenience. This is similar to how Bitwarden suggests you use environment variables to store the client_id and client_secret when engaging in automated workflows from external applications that interface with the Bitwarden CLI in the instances that you want to be able to engage with the automated workflows by tying your session with a session key that rotates based on the timeout mechanism you supply or by manually locking the vault and then later providing your master password to rotate the session key. See here for what I'm referencing in regards to authenticating with the API: https://bitwarden.com/help/cli/#using-an-api-key

With that said, I could implement a feature that allows you the 'option' to save the client_secret, rather than the requirement. In this instance, you would be required to not only provide your master password to authenticate, but you'd also need to provide your client_secret every time to avoid it being stored in WCM. Unless there's a more secure way of storing and making accessible the client_secret outside of WCM that I am not yet aware of. I'm certainly open to suggestions on this!

Let me know if that's a feature you'd like me to implement! As for the logging API, I might pursue that in a future update, but largely created my own in the interim to do some adhoc troubleshooting while I was trying to diagnose various issues with my overall implementation :)

**Comment by Hary309** [comment]
Hi @RedMageKnight,

Thanks for the clarification, I confused secret with master password, sorry for the misunderstanding. 

Thanks for the changes and I wish you bright future!
