### ISSUE TITLE
bw vault fails to unlock

### ISSUE THREAD

**Issue by crazytaj** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#10]
I followed the installation instructions listed here, I installed the bitwarden-cli version 2024.9.0 and downloaded the lastest plugin release here on github. I added the bw.exe to my user-path and configured my client-id and secret in the flow-launcher settings menu. I verified that I could login and unlock my vault from the command line with bw.exe login --apikey and bw.exe unlock masterpassword. However, when I attempt to use the plugin with "bw /unlock masterpassword", the plugin tells me to press enter to confirm the unlock and when I do the search window closes. I never get any system notification that the vault has been unlocked, and if I reopen flow and try to use a "bw" command it still reports the vault is locked. I am not self hosting. Here is the generated log file with all debug levels selected:
[BitwardenFlow_20240922.log](https://github.com/user-attachments/files/17091030/BitwardenFlow_20240922.log)

**Comment by RedMageKnight** [comment]
Hi @crazytaj,

After fiddling with this new version of the CLI (because the virus warnings were going off the chart) I've determined there seems to be an issue with this version of the CLI, although I'm not sure exactly what. Haven't seen virus alerts like this from Windows Defender as I do not use any other 3rd party anti-virus software. I can confirm that version 2024.8.2 does work however, so please use that version for the time being until I see another update from Bitwarden and can test and verify.

**Comment by crazytaj** [comment]
I installed version 2024.8.2 on a fresh install of flow launcher and can also confirm it works as intended, Thanks!
