### ISSUE TITLE
Is there any way you can add caching?

### ISSUE THREAD

**Issue by Etheirystech** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#11]
I would like the search to be instant.

The way I did this was, I would cache the response from "/list/object/items" with TanStack Query.

I used the RESTful API webserver ( bw serve ) since this was the easiest way to get the data, 
and the responses were way faster then the CLI commands, I'm not sure how things are now.

Here's the list of API endpoints if you end up going with the webserver:
https://bitwarden.com/help/vault-management-api/

I'm not sure how secure it is to have the webserver running so maybe when you cache "/list/object/items" you could stop the server,
and start it again when the user wants to clear the cache.

It would also be really nice if you could implement the context menu, here's my example:
![image](https://github.com/user-attachments/assets/c981bd9c-3e6e-4133-b6a9-8dc009af63b0)

**Comment by RedMageKnight** [comment]
Hi @Etheirystech,

The context menu was new to me (didn't even know it existed in Flow Launcher) but this was brought up to me previously and am very interested in implementing this as well so I will be trying to implement this in a future update.

I am currently using the RESTful API for all calls as it is now so that part is already handled.

I like the idea of caching as it would make it much more performant. I already have a syncing mechanism in place and users could initiate that if they want to update their cache like how the official client operates so long as I could cache the credentials securely (TOTP would have to be handled on call as requested, but I don't think that would be much of a lift).

Trust me, I like the ideas, I've just been having a hard time making time for updates as of late. It's on the docket though, I promise you that.

**Comment by Etheirystech** [comment]
No worries, love what you've done so far.

**Comment by RedMageKnight** [comment]
Added to project.
