### ISSUE TITLE
FEATURE REQUEST: Vaultwarden support

### ISSUE THREAD

**Issue by InvitedToHell** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#17]
As far as I understand, this plugin only works with the default bitwarden instance. You CANNOT use API keys from self-hosted vaultwarden instances. Pretty sad.

**Comment by InvitedToHell** [comment]
I've tried setting the server with ``bw server domain.tld`` but I still can't get it to work :/

**Comment by RedMageKnight** [comment]
Hi @InvitedToHell,

This is definitely on my radar to implement. Will need to add some settings in the UI to add self-hosted solution settings in there to reference. I originally designed this to just work for my use cases, but have seen several requests for it so I've got it on the docket. Will just need to spin up my own instance to test things for development.

I will close this for now since I already have a project and task associated to this request. Please be assured that I will work on this.

**Comment by InvitedToHell** [comment]
Thanks for the response nevertheless! Really looking forward to it! If you need help, I may also have a look. You can also reach me on discord if you want to use my instance for testing purposes.
