### ISSUE TITLE
Custom instance URL

### ISSUE THREAD

**Issue by 0PandaDEV** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#5]
Please add support for a custom instance URL, this is the only feature missing for me.

**Comment by RedMageKnight** [comment]
Hi @0PandaDEV!

I'm working on pushing a version 1.3.0 out with some fixes for the API login mechanisms now that Bitwarden's CLI properly supports it. I could try to push this out in a 1.4.0 update, but I don't host my own Vaultwarden or Bitwarden instance anymore so I don't really have a good way to test this. Would you be willing to work with me to ensure the functionality works with a sort of private test build I can send you once I make some headway on it?

**Comment by 0PandaDEV** [comment]
@RedMageKnight 

Sure I would love to test this.

**Comment by flooxo** [comment]
I'm using a self hosted vaultwarden instance with an URL like `https://my.vault.example` and so far the plugin works for me :)

**Comment by 0PandaDEV** [comment]
@flooxo 

How did you do this, where did you set the custom instance URL?

**Comment by 0PandaDEV** [comment]
Never mind just found out I had forgotten to restart Flowlauncher, so the settings were not applied, the custom instance URL can be set with the bw CLI which is required regardless.

**Comment by RedMageKnight** [comment]
Thanks y'all for working through the discussion - I really appreciate the supportive folks that have been communicating with me on my first plugin! I've already got it working now so that it no longer requires interacting with the command-line at all when authenticating, so I've been tweaking it a bit to make the process much more intuitive and feature-rich from the plugin and plugin settings itself.

Appreciate you all :)
