### ISSUE TITLE
feat: Auto-delete copied passwords after pasting

### ISSUE THREAD

**Issue by flooxo** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#6]
### Description
Add a feature that automatically clears copied passwords from the clipboard either after a specified time or immediately after pasting. This will enhance security by reducing the risk of sensitive information being unintentionally exposed. As this function is also available in the Bitwarden App and browser extension, I guess it would be nice to have something similar for this plugin.
For example, I frequently use a clipboard plugin, and it would be very convenient if the passwords I copy could be automatically cleared from the clipboard.

### Feature Solutions
1. **Auto-Clear After Time Interval**:
   - Option to specify a time interval (e.g., 30 seconds, 1 minute, etc.) after which the copied password will be cleared from the clipboard.
   - Configurable via plugin settings.

2. **Auto-Clear After Pasting**:
   - Automatically detect when the copied password has been pasted and clear it from the clipboard immediately (I don't know how easy that is but would be very cool)

![image](https://github.com/user-attachments/assets/2e3057af-af05-4559-a96f-9f120296b6ba)

_This feature is not essential for the functionality of the plugin, but simply improves usability and security_

**Comment by RedMageKnight** [comment]
Hi @flooxo,

This is a great idea - I'll try to sneak this into the update I'm working on for 1.3.0 otherwise, I'll pop this into update 1.4.0 where you can enter your custom server information from the plugin. I've already removed the requirement to need to restart Flow Launcher after putting in the API credentials given the slightly different way the CLI uses it to authenticate against the terminal.

Appreciate the input! And thanks for the comprehensive feature request :)

**Comment by RedMageKnight** [comment]
Hi @flooxo!

I've finally pushed out 1.3.0 and this was one of the features I included, so this should be good to go 😊 I forgot that you also suggested to clear it after pasting, but the timed functionality works. I'll implement that piece in a minor update going forward - thanks for the suggestion!
